SUD/SUD/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView,LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user_interface.urls')),
    path('seller/',include('seller_interface.urls')),
    path('accounts/', include('allauth.urls')),
    #path(''),
    #path('')
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

SUD/seller_interface/models.py
from django.db import models
from django.contrib.auth.models import User
from user_interface.models import User_Profile

from django.urls import reverse

# Create your models here.
class Seller_Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    seller_phone_no=models.PositiveBigIntegerField(default=9999999999)
    def __str__(self):
        return f'{self.user.first_name} {self.seller_phone_no}'

class Restraunt(models.Model):
    of_seller=models.OneToOneField(Seller_Profile,on_delete=models.CASCADE)
    restraunt_name=models.CharField(max_length=15)
    restraunt_rating_value=models.DecimalField(max_digits=3,decimal_places=1)
    def __str__(self):
        return f'{self.restraunt_name}  Rating:{self.restraunt_rating_value}'

class Item(models.Model):
    of_restraunt=models.ForeignKey(Restraunt,on_delete=models.CASCADE)
    item_price=models.PositiveBigIntegerField(default=0)
    item_name=models.CharField(max_length=25)
    item_description=models.TextField()
    item_image=models.ImageField(upload_to='item_images/',null=True,blank=True)
    available=models.BooleanField(default=True)
    item_rating=models.DecimalField(max_digits=3,decimal_places=1,default=5.0)
    def __str__(self):
        return f'{self.item_name}   {self.item_price}   Rating:{self.item_rating}'
    def get_absolute_url(self):
        return reverse('order-list')


class Pending_Order(models.Model):
    of_student=models.ForeignKey(User_Profile,on_delete=models.CASCADE)
    order_price=models.PositiveBigIntegerField(default=0)
    no_of_items=models.PositiveIntegerField(default=0)
    order_to=models.ForeignKey(Restraunt,on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.of_student}      {self.order_price}  {self.no_of_items}'

class Pending_Order_Item(models.Model):
    of_order=models.ForeignKey(Pending_Order,on_delete=models.CASCADE)
    item_price=models.PositiveBigIntegerField(default=0)
    item_name=models.CharField(max_length=25)
    item_quantity=models.PositiveIntegerField(default=1)
    def __str__(self):
        return f'{self.item_name}   {self.of_order.of_student}'


class Rating(models.Model):
    rating_value=models.IntegerField(default=5)
    rating_by=models.ForeignKey(User,on_delete=models.CASCADE)
    rated_item=models.ForeignKey(Item,on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.rated_item}  {self.rating_by}    {self.rating_value}'

class Restraunt_rating(models.Model):
    rating_value=models.IntegerField(default=5)
    rating_by=models.ForeignKey(User,on_delete=models.CASCADE)
    rated_restraunt=models.ForeignKey(Restraunt,on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.rated_restraunt.restraunt_name}      {self.rating_by}    {self.rating_value}'



SUD/user_interface/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from allauth.socialaccount.models import SocialAccount, SocialApp

hostels=(('SR','SR'),
         ('GANDHI','GANDHI'),
         ('KRISHNA','KRISHNA'),
         ('RAM','RAM'),
         ('BUDH','BUDH'),
         ('SHANKAR','SHANKAR'),
         ('VYAS','VYAS'),
         ('RANAPRATAP','RANAPRATAP'),
         ('VK','VK'),
         ('ASHOK','ASHOK'),
         ('MEERA','MEERA'),
         ('BHAGIRATH','BHAGIRATH')
        
         
         
         )
branches=(

    ("A7","CS"),
    ("AA","ECE"),
    ("A8","ENI"),
    ("A3","EEE"),
    ("A4","MECH"),
    ("AB","MANU"),
    ("A2","CIVIL"),
    ("A1","CHEMICAL"),
    ("B5","Msc. PHY"),
    ("B1","Msc. BIO"),
    ("B2","Msc. CHEM"),
    ("A5","PHARMA"),
    ("B4","Msc. MATH"),
    ("B3","Msc. ECO"),
    ("B3","Msc. ECO")


    )
# Create your models here.
class User_Profile(models.Model):
    name=models.CharField(max_length=15)
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    bits_id=models.CharField(max_length=15)
    hostel=models.CharField(max_length=10,choices=hostels,default='SR')
    room_no=models.PositiveIntegerField(default=100)
    user_branch=models.CharField(max_length=20,choices=branches,default="A7")


    def __str__(self):
        return f'{self.bits_id}     {self.hostel}   {self.room_no}'

class Basket(models.Model):
    from seller_interface.models import Restraunt
    owner=models.OneToOneField(User_Profile,on_delete=models.CASCADE)
    no_of_items=models.PositiveIntegerField(default=0)
    total_cost=models.PositiveBigIntegerField(default=0)
    of_restraunt=models.ForeignKey(Restraunt,on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.owner.bits_id}   {self.no_of_items}      {self.total_cost}'
class Basket_Item(models.Model):
    basket=models.ForeignKey(Basket,on_delete=models.CASCADE)
    item_quantity=models.PositiveIntegerField(default=1)
    item_cost=models.PositiveBigIntegerField(default=0)
    item_name=models.CharField(max_length=25)
    item_description=models.TextField()
    item_image=models.ImageField(upload_to='item_images/',null=True,blank=True)
    def __str__(self):
        return f'{self.item_name}   {self.item_quantity}'
    @property
    def total_cost_item(self):
        return self.item_cost*self.item_quantity



SUD/templates/add-item.html
{% extends 'base2.html' %}

{% block content %}
  <div class="container mt-5">
    <h1>Add Item to Restaurant</h1>

    <form method="post" action="">
      {% csrf_token %}
      
      <div class="form-group">
        <label for="{{ form.item_name.id_for_label }}">Item Name:</label>
        {{ form.item_name }}
      </div>

      <div class="form-group">
        <label for="{{ form.item_price.id_for_label }}">Item Price:</label>
        {{ form.item_price }}
      </div>

      <div class="form-group">
        <label for="{{ form.description.id_for_label }}">Description:</label>
        {{ form.item_description }}
      </div>
      <div class="form-group">
        <label for="{{ form.description.id_for_label }}">Image</label>
        {{ form.item_image }}
      </div>

      <!-- Add more form fields as needed -->

      <button type="submit" class="btn btn-primary">Add</button>
    </form>
  </div>
{% endblock %}

SUD/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>BitsExpress</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href={% url 'res-list' %}>BitsExpress</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
           
            <li class="nav-item">
              <a class="nav-link" href="">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={%url 'view-basket' %}>Basket</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={%url 'logout' %}>Logout</a>
            </li>
             
          </ul>
        </div>
      </nav>
      <div class="container">
        {% if messages %}
          {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% endif %}
                            {% if message.tags == 'success' %}alert-success{% endif %}
                            {% if message.tags == 'info' %}alert-info{% endif %}
                            {% if message.tags == 'warning' %}alert-warning{% endif %}" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
    
        
      </div>
   
   {%block content%}
   {%endblock%}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
</body>
</html>

SUD/templates/base2.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <title>BitsExpress-Seller</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{%url 'order-list' %}">BitsExpress-Seller</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      
      <li class="nav-item">
        <a class="nav-link" href="{%url 'item-list' %}">View Items</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={%url 'add-item' %}>Add Item</a>
      </li>
     
      
    </ul>
    <ul class="navbar-nav ml-auto">
     
      <li class="nav-item">
        <a class="nav-link" href={%url 'logout' %}>Logout</a>
      </li>
    </ul>
  </div>
</nav>
{% if messages %}
          {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-danger{% endif %}
                            {% if message.tags == 'success' %}alert-success{% endif %}
                            {% if message.tags == 'info' %}alert-info{% endif %}
                            {% if message.tags == 'warning' %}alert-warning{% endif %}" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
{%block content%}
   {%endblock%}



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

SUD/templates/basket.html


{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h1>Your Basket</h1>

    {% if basket and basket.basket_item_set %}
    <h1>{{basket.of_restraunt.restraunt_name}}</h1>
      <table class="table mt-3">
        <thead>
          <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Price</th>
            <th>Remove</th>
            <th>Rate Item</th>
            
          </tr> 
        </thead>
        <form action='rate/{{basket.pk}}/' method="post">{%csrf_token%}
        <tbody>
          {% for item in basket.basket_item_set.all %}
            <tr>
              <td>{{ item.item_name }}</td>
              <td>{{ item.item_quantity }}</td>
              <td>${{ item.item_cost }}</td>
             
              <td>{{item.total_cost_item  }}</td>
    
          
             
              <td>
                <a href="{%url 'remove-item' item.pk%}" class="btn btn-danger btn-sm">Remove</a>
              </td>
              <td> <input type="range" class="form-control-range" id="slider" name="slider{{item.pk}}" min="0" max="10" step="1">
              </td>
            </tr>
          {% endfor %}

        </tbody>
        <tfoot>
          <tr>
            <td colspan="3"></td>
            <td>Total: ${{ basket.total_cost }}</td>
            <td></td>
            <td ><button type="submit" class="btn btn-info btn-sm">Rate</button></td></form>
          </tr>
        </tfoot>
      </table>

      <a href={%url 'place-order' %} class="btn btn-primary">Proceed to Checkout</a>
    {% else %}
      <p>Your cart is empty.</p>
    {% endif %}
  </div>
{% endblock %}

SUD/templates/home.html
{%extends 'base.html' %}
{% load socialaccount %}
{%block content%} 
{%if user.is_authenticated%}
{% if res_list %}
    <div class="container mt-4">
        <h2 class="mb-3">Restaurant List</h2>
        {% for res in res_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'res-detail' res.pk %}">{{ res.restraunt_name }}</a>
                    </h5>
                    <p class="card-text">Rating: {{ res.restraunt_rating_value }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}


{%else%}
<div class="col-lg-4 col-md-6 col-sm-12 mb-4">
  <div class="border rounded p-3" style="background-color: lavender; height: 300px;">
      <div class="text-center text-white" style="font-size: xx-large;">STUDENT LOGIN</div>

      <figure class="text-center">
          <blockquote class="blockquote">
              <p><h1>Login with BitsMail</h1></p>
          </blockquote>
          <figcaption>
              <a href="{% provider_login_url 'google' %}" class="btn btn-info"><h1>Login</h1></a>
          </figcaption>
      </figure>
      
      <div class="mt-3">
          <a href="{% url 'seller-login' %}" class="text-black">Seller Login</a>
      </div>
  </div>
</div>

  {%endif%}
  {%endblock%}

SUD/templates/login.html
{% extends "base2.html" %}
{% block content %}
<div class="container mt-5">
    <legend>
        <div class="content-section" style="background-color: blue;">
            <fieldset class="text-center border p-4" style="max-width: 400px; margin: 0 auto; background-color: white;">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary mt-3">Login</button>
                </form>
            </fieldset>
            <div class="text-center mt-3">
                <small>NEW SELLER? <a href="{% url 'seller-form' %}">Sign Up</a></small>
            </div>
        </div>
    </legend>
</div>
{% endblock %}

             

SUD/templates/logout.html
{%extends "base.html"%}
{%block content%}

<h2 style="text-align: center; color: white;" >You have been logged out!!</h2>
   
<h3 style="text-align: center;" >>Want to login? <a href="{% url 'home' %}" style="font-weight: 600;"> Login</a></h3>
{% endblock %}

SUD/templates/order-detail.html
{% extends 'base2.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Pending Order Details</h2>

    <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title">Order Number: {{ order.pk }}</h5>
            <p class="card-text">For: {{ order.of_student.bits_id }}</p>
            <p class="card-text">TO: {{ order.of_student.hostel }}:{{order.of_student.room_no}}</p>


            <h6 class="mt-3">Items:</h6>
            <ul class="list-group">
                {% for item in order.pending_order_item_set.all %}
                    <li class="list-group-item">
                        {{ item.item_name }} - Quantity: {{ item.item_quantity }} - Price: {{ item.item_price }}
                    </li>
                {% endfor %}
            </ul>

            <div class="mt-3">
                <p class="font-weight-bold">Total Price: ${{ order.total_cost }}</p>
                <p>Status: <span class="badge badge-warning">Pending</span></p>
            </div>
        </div>
    </div>

    <a href="{% url 'order-list' %}" class="btn btn-primary mt-3">Back to Orders</a>
    <a href="{% url 'send-order' order.pk %}" class="btn btn-primary mt-3">Order Prepared and Ready to Send</a>

</div>
{% endblock %}

SUD/templates/res-detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card" style="background-color: lightblue;">
        <h1 class="card-title">{{ res.restraunt_name }}</h1>
        <h2 class="card-title">Rating:{{res.restraunt_rating_value}}</h2>
        <div class="card-body">
            <h2>Items Available</h2>
            {% for item in res.item_set.all %}
                <div class="mb-3">
                    <ul class="list-unstyled">
                        <li>{{ item.item_name }}</li>
                        <li>Price: {{ item.item_price }}</li>
                        {% if item.item_image %}
                        <div class="mt-3">
                            <img src="{{ item.item_image.url }}" alt="{{ item.item_name }}" class="img-fluid rounded" style="max-height: 300px; max-width: 300px;">
                        </div>
                    {% endif %}
                    <li>Rating:{{item.item_rating}}</li>
                    </ul>
                    <a href="{% url 'add-to-basket' item.pk %}" class="btn btn-primary">Add to Basket</a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="card mt-4">
        <div class="card-body" style="background-color: lightgray;">
            <h2>Rate the Restaurant</h2>
            <form action="{% url 'rate-restaurant' res.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="restaurantRating">Rating:</label>
                    <input type="range" class="form-control-range" id="restaurantRating" name="restaurantRating" min="0" max="10" step="1">
                </div>
                <button type="submit" class="btn btn-success">Submit Rating</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}



SUD/templates/seller-home.html
{% extends 'base2.html' %}

{% block content %}
{% if seller_restraunt%}
{% if pending_order_list %}
  <div class="container mt-5">
    <h1 class="mb-4">Pending Orders</h1>

    
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Order No.</th>
            <th>Ordered By</th>
            <th>To Hostel</th>
            <th>Room no.</th>
            <th>Total Amount</th>
            
          </tr>
        </thead>
        <tbody>
          {% for order in pending_order_list %}
            <tr>
              <td>{{ order.pk }}</td>
              <td><a href="{%url 'order-detail' order.pk %}">{{ order.of_student.bits_id }}({{ order.of_student.user.first_name}})</a></td>
              <td>{{ order.of_student.hostel }}</td>
              <td>{{order.of_student.room_no}}</td>
              <td>{{ order.order_price }}</td>
              
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="alert alert-info">No pending orders.</p>
    
  </div>{% endif %}

 <p class="alert alert-info">Your restaurant is rated {{seller_restraunt.restraunt_rating_value}}/10</p>
{%endif%}
  {%endblock %}


SUD/templates/seller-signuppage.html
{%extends 'base2.html' %}
{%block content%}
<legend>
    <div class="content-section" style="text-align: center; border-color: red;border-width: 45px; "  >
            <fieldset >
                <form method="post">
                    {%csrf_token%}
            
                 {{form.as_p}}
            
            
            
                
                
            </fieldset>
            <div><button type="submit">SIGN UP</button><br></form></div>
              <div><small>already have an account? <a href="{% url 'seller-login' %}"> sign in</a></small></div>
            </div>
        </div></legend>
        {%endblock%}

SUD/templates/view-items.html
{%extends 'base2.html'%}
{%block content%}
<div class="card-body">
    <h2>Items Available</h2>
    {% for item in item_list %}
        <div class="mb-3">
            <ul class="list-unstyled" style="background-color: palegoldenrod;">
                <li>{{ item.item_name }}</li>
                <li>Price: {{ item.item_price }}</li>
                {% if item.item_image %}
                <div class="mt-3">
                    <img src="{{ item.item_image.url }}" alt="{{ item.item_name }}" class="img-fluid rounded" style="max-height: 300px; max-width: 300px;">
                </div>
            {% endif %}
            <li>Rating:{{item.item_rating}}</li>
            </ul>
            <a href="{% url 'item-update' item.pk %}" class="btn btn-primary">Update</a>
        </div>
    {% endfor %}
    <a href="{% url 'add-item'  %}" class="btn btn-primary">Add Item</a>

</div>

{%endblock%}